docker.io:
  images:
    gitlab/gitlab-ee:
      - 18.6.1-ee.0
    gitlab/gitlab-runner:
      - v18.6.2
    sonatype/nexus3:
      - 3.86.2
    jenkins/jenkins:
      - 2.539
    hanchuanchuan/goinception:
      - latest
    hhyo/archery:
      - v1.13.0
    redis:
      - 7
    mysql:
      - 8
    postgres:
      - 15
    percona/percona-xtrabackup:
      - 8.4
    nginx:
      - 1.29
    grafana/mimir:
      - 2.17.2
    grafana/promtail:
      - 3.6
    grafana/loki:
      - 3.6
    grafana/grafana:
      - 12.3
    prom/prometheus:
      - v3.7.3
    prom/pushgateway:
      - v1.11.2
    prom/alertmanager:
      - v0.29.0
    minio/minio:
      - RELEASE.2025-09-07T16-13-09Z
    uozi/nginx-ui:
      - 2.2.1
    sonarqube:
      - 25.11.0.114957-community
    jupyter/datascience-notebook:
      - latest
    dreamacro/clash:
      - latest
    xiaojusurvey/xiaoju-survey:
      - 1.3.4
    aidencro/openmaxio-webui:
      - v1.7.6
    php:
      - 7.4.33-fpm
