docker.io:
  images:
    gitlab/gitlab-ee:
      - 18.8.2-ee.0
    gitlab/gitlab-runner:
      - v18.8.0
    sonatype/nexus3:
      - 3.87.2
    jenkins/jenkins:
      - 2.548
    hanchuanchuan/goinception:
      - latest
    hhyo/archery:
      - v1.13.0
    redis:
      - 7
    mysql:
      - 8
    postgres:
      - 15
    percona/percona-xtrabackup:
      - 8.4
    nginx:
      - 1.29
    grafana/mimir:
      - 2.17.5
    grafana/promtail:
      - 3.6
    grafana/loki:
      - 3.6
    grafana/grafana:
      - 12.3
    prom/prometheus:
      - v3.9.1
    prom/pushgateway:
      - v1.11.2
    prom/alertmanager:
      - v0.30.1
    minio/minio:
      - RELEASE.2025-09-07T16-13-09Z
    minio/mc:
      - latest
    uozi/nginx-ui:
      - 2.3.2
    sonarqube:
      - 26.1.0.118079-community
    jupyter/datascience-notebook:
      - latest
    dreamacro/clash:
      - latest
    xiaojusurvey/xiaoju-survey:
      - 1.3.4
    aidencro/openmaxio-webui:
      - v1.7.6
    php:
      - 7.4.33-fpm
    apacherocketmq/rocketmq-dashboard:
      - 1.0.0
